version: '3.8'

services:
  backend:
    build: ./Expenzor_Backend
    container_name: expenzor_backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./Expenzor_Frontend
    container_name: expenzor_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
